# Generated by Django 5.0 on 2023-12-23 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
